"""create matakuliah table

Revision ID: 4587ca1612f5
Revises: dc01a411d567
Create Date: 2025-05-15 20:51:55.209469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4587ca1612f5'
down_revision = 'dc01a411d567'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
