"""recreate matakuliah table

Revision ID: ca1c03266e4f
Revises: 4587ca1612f5
Create Date: 2025-05-15 21:08:24.120492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1c03266e4f'
down_revision = '4587ca1612f5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.Text(), nullable=False),
    sa.Column('nama_mk', sa.Text(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matakuliah')),
    sa.UniqueConstraint('kode_mk', name=op.f('uq_matakuliah_kode_mk'))
    )
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kode_mk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nama_mk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_mahasiswa'),
    sa.UniqueConstraint('kode_mk', name='uq_mahasiswa_kode_mk', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
