"""recreate matakuliah table

Revision ID: ca9b1a17a6ba
Revises: ef0b70814ba0
Create Date: 2025-05-15 21:16:03.894433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9b1a17a6ba'
down_revision = 'ef0b70814ba0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
