"""recreate matakuliah table

Revision ID: 771c7866f867
Revises: ca9b1a17a6ba
Create Date: 2025-05-15 21:24:39.925229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771c7866f867'
down_revision = 'ca9b1a17a6ba'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
