"""recreate matakuliah table

Revision ID: de9fabaf6f29
Revises: 7aec6e849b28
Create Date: 2025-05-15 21:34:52.435924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9fabaf6f29'
down_revision = '7aec6e849b28'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
