"""recreate matakuliah table

Revision ID: ef0b70814ba0
Revises: ca1c03266e4f
Create Date: 2025-05-15 21:08:45.407926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0b70814ba0'
down_revision = 'ca1c03266e4f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
