"""recreate matakuliah table

Revision ID: 7aec6e849b28
Revises: 771c7866f867
Create Date: 2025-05-15 21:33:04.961370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aec6e849b28'
down_revision = '771c7866f867'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
